sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker build -t sites.azurecr.io/site-miotars .
  - docker login -u sites -p "$DOCKER_PASSWORD" sites.azurecr.io

script:
  - docker push sites.azurecr.io/site-miotars